name: Test, Upload Coverage and Release Rust

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Fontconfig
        run: |
          sudo apt-get update
          sudo apt install -y pkg-config libfreetype6-dev libfontconfig1-dev

      - name: Run Tests and Upload Coverage
        uses: Reloaded-Project/devops-rust-test-and-coverage@v1
        # Currently unsupported due to no native runner.
        # Native runner currently only available in enterprise.
        if: matrix.target != 'aarch64-pc-windows-msvc'
        with:
          upload-coverage: true
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
      # Note: The GitHub Runner Images will contain an up to date Rust Stable Toolchain
      #       thus as per recommendation of cargo-semver-checks, we're using stable here.
      #
      # Note to reader. If adding this to a new repo, please clear cache.
      - name: Run cargo-semver-checks
        if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          SEARCH_RESULT=$(cargo search "^struct-compression-analyzer$" --limit 1)

          if echo "$SEARCH_RESULT" | grep -q "^struct-compression-analyzer "; then
            rustup target add ${{ matrix.target }}
            cargo install cargo-semver-checks
            cargo semver-checks --target ${{ matrix.target }} 
          else
              echo "No previous version found on crates.io. Skipping semver checks."
          fi

  publish-crate:
    permissions:
      contents: write

    needs: [build-and-test]
    # Publish only on tags
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Install Fontconfig
        run: |
          sudo apt-get update
          sudo apt install -y pkg-config libfreetype6-dev libfontconfig1-dev

      - name: Publish Rust Crate and Artifacts  
        uses: Reloaded-Project/devops-publish-action@v1
        with:
          crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
          rust-project-paths: |
            src/struct-compression-analyzer
            src/struct-compression-analyzer-cli